"""Pomodoro plan + coaching endpoints."""

from datetime import date

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.middleware.auth import get_active_user
from app.middleware.rate_limit import daily_ai_rate_limiter
from app.models import User
from app.schemas.ai import (
    PomodoroCoachingRequest,
    PomodoroCoachingResponse,
    PomodoroRequest,
    PomodoroResponse,
)
from app.services.beta_codes import resolve_effective_tier

from ._common import _get_incomplete_tasks, _log_empty_short_circuit

router = APIRouter()


# Rate limiters are looked up at call time via the package module so
# tests can patch ``app.routers.ai.X`` and have their stub take effect
# (a top-level ``from ._common import X`` would bind the name at import
# time and bypass the patch).


@router.post("/pomodoro-plan", response_model=PomodoroResponse)
async def plan_pomodoro(
    data: PomodoroRequest,
    request: Request,
    current_user: User = Depends(get_active_user),
    db: AsyncSession = Depends(get_db),
):
    from app.routers import ai as _ai_pkg
    _ai_pkg.ai_rate_limiter.check(request, is_admin=current_user.is_admin)
    tier = await resolve_effective_tier(current_user, db)
    daily_ai_rate_limiter.check(current_user.id, tier, is_admin=current_user.is_admin)

    tasks = await _get_incomplete_tasks(current_user)
    if not tasks:
        _log_empty_short_circuit(current_user, "pomodoro")
        return PomodoroResponse(
            sessions=[],
            total_sessions=0,
            total_work_minutes=0,
            total_break_minutes=0,
            skipped_tasks=[],
        )

    task_dicts = [t.to_ai_dict() for t in tasks]

    try:
        from app.services.ai_productivity import plan_pomodoro as ai_plan

        plan = ai_plan(
            tasks=task_dicts,
            available_minutes=data.available_minutes,
            session_length=data.session_length,
            break_length=data.break_length,
            long_break_length=data.long_break_length,
            focus_preference=data.focus_preference,
            today=date.today(),
            tier=tier,
        )
    except RuntimeError:
        raise HTTPException(status_code=503, detail="AI service temporarily unavailable")
    except ValueError:
        raise HTTPException(status_code=500, detail="AI returned an invalid response")

    return PomodoroResponse(**plan)


@router.post("/pomodoro-coaching", response_model=PomodoroCoachingResponse)
async def pomodoro_coaching(
    data: PomodoroCoachingRequest,
    request: Request,
    current_user: User = Depends(get_active_user),
    db: AsyncSession = Depends(get_db),
):
    """A2 Pomodoro+ coaching — pre-session, break-activity, or session-recap.

    Returns a single coaching sentence generated by Haiku. Trigger is dispatched
    inside ``generate_pomodoro_coaching``; only the fields relevant to the
    trigger are consulted.
    """
    from app.routers import ai as _ai_pkg
    _ai_pkg.pomodoro_coaching_rate_limiter.check(request, is_admin=current_user.is_admin)
    tier = await resolve_effective_tier(current_user, db)
    daily_ai_rate_limiter.check(current_user.id, tier, is_admin=current_user.is_admin)

    try:
        from app.services.ai_productivity import generate_pomodoro_coaching as ai_coaching

        message = ai_coaching(
            trigger=data.trigger,
            upcoming_tasks=(
                [t.model_dump() for t in data.upcoming_tasks] if data.upcoming_tasks else None
            ),
            session_length_minutes=data.session_length_minutes,
            elapsed_minutes=data.elapsed_minutes,
            break_type=data.break_type,
            recent_suggestions=data.recent_suggestions,
            completed_tasks=(
                [t.model_dump() for t in data.completed_tasks] if data.completed_tasks else None
            ),
            started_tasks=(
                [t.model_dump() for t in data.started_tasks] if data.started_tasks else None
            ),
            session_duration_minutes=data.session_duration_minutes,
            tier=tier,
        )
    except RuntimeError:
        raise HTTPException(status_code=503, detail="AI service temporarily unavailable")
    except ValueError:
        raise HTTPException(status_code=500, detail="AI returned an invalid response")

    return PomodoroCoachingResponse(message=message)
